name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    name: Run PHPUnit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a81bbbf8298c0fa03ea29cdc473d45769f953675

      - name: Build Docker containers
        run: docker-compose build

      - name: Run tests
        run: docker-compose run --rm composer test
